services:
  nextjs:
    image: harbor.exove.eu/exove-demos/exove-vendure-nextjs:latest
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - nextjs_build_secrets
      network: host
    restart: unless-stopped
    container_name: nextjs
    networks:
      - store_net
    env_file:
      - .env
    ports:
      - 127.0.0.1:3001:3000

networks:
  store_net:
    external: true

secrets:
  nextjs_build_secrets:
    file: .env
