name: Build and publish NextJS image

on:
  workflow_dispatch:

jobs:
  build-push-image:
    name: Build Next.js container
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.REGISTRY_HOST }}/exove-demos/exove-vendure-nextjs
          tags: |
            latest
            # branch name
            type=ref,event=branch
            # short commit sha
            type=sha,prefix=sha-
            # full commit sha
            type=sha,prefix=sha-,format=long

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
